spring:
  application:
    name: product-manager
  datasource:
    url: jdbc:mariadb://localhost:3306/product-manager
    username: root
    password: Admin12345
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    org:
      springframework:
        security: DEBUG
flyway:
  url: jdbc:mariadb://localhost:3306/product-manager
  schemas: product-manager
  user: "root"
  password: "Admin12345"